version: '3'
services:
  web:
    image: server
    container_name: web
    command: bash -c "gunicorn community.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    networks:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certbot/conf:/etc/letsencrypt
      - ./cert/certbot/www:/var/www/certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - server
    environment:
      # 환경 변수 추가
      - CORS_ORIGIN_WHITELIST=http://localhost:3000,http://127.0.0.1:8000,http://localhost:5173,http://fitmap.store
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./cert/certbot/conf:/etc/letsencrypt 
      - ./cert/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  server:
